# Generated by Django 5.0.1 on 2024-01-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('attendance', models.PositiveIntegerField()),
                ('assignment', models.PositiveIntegerField()),
                ('marks', models.PositiveIntegerField()),
                ('comments', models.TextField()),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress_tracker.trainee')),
            ],
        ),
    ]
